### ISSUE TITLE
Gorilla CSRF always sets the same cookie, even as csrf.Token(r) varies

### ISSUE THREAD

**Issue by francoposa** [gorilla/csrf#158]
I cannot get any version of the documentation working with Javascript.
I run a get with Axios to set the header on the axios instance, then I post with the header and cookie included.
The problem is that the csrf cookie that Gorilla sets is always the same cookie, every single time, across restarts, and browsers, and curl, and Postman, it is always `_gorilla_csrf=MTYzNzEwOTA5NHxJbkYwVGk5VFpVcFVWQ3RYV0ZOeU0yWjFRa3d5T0RoTVUycGtjbkZhU2pGd1p6ZDVNamxRWVcxV2FFRTlJZ289fLeqCKHNIBazzPu_ILjc2dkBBbeqBjy52MgsxkeVOvfg; HttpOnly; SameSite=Lax`

Therefore I can never successfully POST, because my header (always regenerated and fresh) and cookie (always the same) never match.

Here is my code, stripped down as much as possible. I use Chi router because it is what I am familiar with, but that difference from the docs should not matter here.

Go (`go version go1.17.2 darwin/amd64`):
```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
	"github.com/gorilla/csrf"
	"github.com/rs/cors"
)

func main() {
	router := chi.NewRouter()

	// Suggested basic middleware stack from chi's docs
	router.Use(middleware.RequestID)
	router.Use(middleware.RealIP)
	router.Use(middleware.Logger)
	router.Use(middleware.Recoverer)

	CSRF := csrf.Protect(
		[]byte("place-your-32-byte-long-key-here"),
		csrf.RequestHeader("X-CSRF-Token"),
		csrf.Secure(false),
		csrf.TrustedOrigins([]string{"*"}),
		csrf.MaxAge(0),
	)

	// Routing to API handlers
	router.Route("/api", func(router chi.Router) {
		router.With(CSRF).Get("/", Get)
		router.With(CSRF).Post("/", Post)
	})

	corsRouter := cors.New(cors.Options{
		AllowCredentials: true,
		AllowedHeaders:   []string{"Content-Type", "X-CSRF-Token"},
		ExposedHeaders:   []string{"Content-Type", "X-CSRF-Token"},
		AllowedMethods:   []string{"GET", "POST", "OPTIONS"},
		AllowedOrigins:   []string{"*"},
		Debug:            true,
	}).Handler(router)

	srv := &http.Server{
		Handler:      corsRouter,
		Addr:         "localhost" + ":" + "8000",
		ReadTimeout:  time.Duration(15) * time.Second,
		WriteTimeout: time.Duration(10) * time.Second,
		IdleTimeout:  time.Duration(5) * time.Second,
	}

	fmt.Printf("starting http server on port %s...\n", "8000")
	log.Fatal(srv.ListenAndServe())

}


func Get(w http.ResponseWriter, r *http.Request) {
	w.Header().Add("X-CSRF-Token", csrf.Token(r))
}

func Post(w http.ResponseWriter, r *http.Request) {}
```

Javascript:
```javascript
let get = async() => {
    let csrfToken = ""
    try {
        let resp = await axios.get("http://localhost:8000/api/")
        console.log(resp)
        console.log(resp.headers)
        csrfToken = resp.headers["x-csrf-token"]
        console.log(csrfToken)
    } catch (err) {
        // Handle the exception
        console.log(err)
    }

    const instance = axios.create({
        headers: {"X-CSRF-Token": csrfToken}
    })
    console.log(instance)
    return instance
}

let post = async(instance) => {
    try {
        let resp = await instance.post("http://localhost:8000/api/", {})
        console.log(resp)
    } catch (err) {
        console.log(err)
    }
}

get()
    .then(axiosInstance => {
        post(axiosInstance)
    })
```

**Comment by francoposa** [comment]
The error always comes from `csrf.go`, line 216:

```realToken, err := cs.st.Get(r)```

err is always "http: named cookie not present"

So it seems that axios is not sending it?

**Comment by masayomitan** [comment]
someone know it?

**Comment by francoposa** [comment]
I actually figured this out, at least for serving on localhost: https://github.com/francoposa/go-csrf-examples
It's about the CORS settings, here's what I use for the API server (see `config.local.yaml` files in repo)

```yaml

---
server:
  host: localhost
  port: 8080
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5
  cors:
    allowCredentials: true
    allowedHeaders:
      - X-CSRF-Token
    exposedHeaders:
      - X-CSRF-Token
    allowedOrigins:
      - http://localhost*
    debug: true
  csrf:
    secure: false  # false in development only!
    key: place-your-32-byte-long-key-here
    cookieName: csrf
    header: X-CSRF-Token
```
